export const getFireReportDefaults = (report = null) => ({
    id: report?.id,
    report_type_id: report?.report_type_id,
    is_error_card: report?.is_error_card,
    type_of_fire_protection: report?.type_of_fire_protection,
    object_id: report?.object_id,
    object_type_id: report?.object_type_id,
    plan: report?.plan,
    rank: report?.rank,
    card_number: report?.card_number,
    shift: report?.shift,
    water_consumption: report?.water_consumption,
    first_water_barrel_minutes: report?.first_water_barrel_minutes,
    water_source: report?.water_source,
    dead_total: report?.dead_total,
    dead_children: report?.dead_children,
    dead_staff: report?.dead_staff,
    injured_total: report?.injured_total,
    injured_children: report?.injured_children,
    injured_staff: report?.injured_staff,
    rescued_children: report?.rescued_children,
    rescued_staff: report?.rescued_staff,
    violated_children: report?.violated_children,
    violated_staff: report?.violated_staff,
    info: report?.info ?? {
        observed_consequences: '',
        time_estimation: '',
        characteristics_of_roads: '',
        characteristics_of_conditions: '',
        evacuation_possibility: '',
        has_paople: '',
        has_gas: '',
        object_owner: '',
        ownership: '',
        additional_info: '',
        plan: '',
        message: '',
        damage: '',
        rescued: '',
        square: '',
        distance: '',
        operational_interest: '',
        corrections: '',
    },
    barrels: report?.barrels ?? [],
    fire_extinguishing_agents: report?.fire_extinguishing_agents ?? [],
    rtp: report?.rtp ?? [],
    personnel: report?.personnel ?? [],
    gdzs: report?.gdzs ?? [],
    cause_id: report?.cause_id,
    localized_at: report?.localized_at,
    fire_eliminated_at: report?.fire_eliminated_at,
    elimination_at: report?.elimination_at,
});
