export const getFireReportDefaults = (report = null) => ({
    id: report?.id ?? null,
    report_type_id: report?.report_type_id ?? null,
    is_error_card: report?.is_error_card ?? false,
    type_of_fire_protection: report?.type_of_fire_protection ?? null,
    object_id: report?.object_id ?? null,
    object_type_id: report?.object_type_id ?? null,
    plan: report?.plan ?? null,
    rank: report?.rank ?? null,
    card_number: report?.card_number ?? null,
    shift: report?.shift ?? null,
    water_consumption: report?.water_consumption ?? null,
    first_water_barrel_minutes: report?.first_water_barrel_minutes ?? null,
    water_source_id: report?.water_source_id ?? null,
    dead_total: report?.dead_total ?? null,
    dead_children: report?.dead_children ?? null,
    dead_staff: report?.dead_staff ?? null,
    injured_total: report?.injured_total ?? null,
    injured_children: report?.injured_children ?? null,
    injured_staff: report?.injured_staff ?? null,
    rescued_children: report?.rescued_children ?? null,
    rescued_staff: report?.rescued_staff ?? null,
    violated_children: report?.violated_children ?? null,
    violated_staff: report?.violated_staff ?? null,
    info: report?.info ?? {
        observed_consequences: '',
        time_estimation: '',
        characteristics_of_roads: '',
        characteristics_of_conditions: '',
        evacuation_possibility: '',
        has_paople: '',
        has_gas: '',
        object_owner: '',
        ownership: '',
        additional_info: '',
        plan: '',
        message: '',
        damage: '',
        rescued: '',
        square: '',
        distance: '',
        operational_interest: '',
        corrections: '',
    },
    barrels: report?.barrels ?? [],
    fire_extinguishing_agents: report?.fire_extinguishing_agents ?? [],
    rtp: report?.rtp ?? [],
    personnel: report?.personnel ?? [],
    gdzs: report?.gdzs ?? [],
    cause_id: report?.cause_id ?? null,
    localized_at: report?.localized_at ?? null,
    fire_eliminated_at: report?.fire_eliminated_at ?? null,
    elimination_at: report?.elimination_at ?? null,
    departments: report?.departments ?? []
});
